# Generated by Django 3.1.7 on 2021-05-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_pricipal', '0004_auto_20210524_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bdcpf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpfbd', models.IntegerField(max_length=11)),
            ],
        ),
    ]
