# Generated by Django 3.1.7 on 2021-06-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_pricipal', '0004_auto_20210616_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
