# Generated by Django 3.1.7 on 2021-05-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_pricipal', '0006_auto_20210524_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdcpf',
            name='cpfbd',
            field=models.CharField(max_length=11),
        ),
    ]
