# Generated by Django 3.1.7 on 2021-07-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_pricipal', '0007_auto_20210706_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
