# Generated by Django 3.1.7 on 2021-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_pricipal', '0008_auto_20210602_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, db_column='Curso', max_length=11, verbose_name='Curso'),
        ),
    ]
